### ISSUE TITLE
małymi kroczkami do przodu :)

### ISSUE THREAD

**Issue by JoannaKu** [JoannaKu/Java-Script-2#1]
Nie wiem dlaczego nie działa mi kompilacja sass. Jak wpisuje w terminalu polecenie "grunt" to nie wyskakuje żaden błąd, ale css się nie zmienia i jest pusty...

**Comment by michal-bootcamp** [comment]
dwa razy w Gruntfile definiujesz task 'default' i ten drugi nadpisuje pierwszy

**Comment by JoannaKu** [comment]
poprawiłam, ale nadal nic się nie dzieje

**Comment by michal-bootcamp** [comment]
zmien sciezki do plikow sass/css w Gruntfile na relatywne, czyli wyobraz sobie, ze chcesz dostac sie do pliku z miejsca gdzie masz Gruntfile. Np jesli plik sass masz w tym samym katalogu, co Gruntfile, to sciezka powinna wygladac tak: `style.scss`. Jesli masz plik w katalogu `sass`, to sciezka bedzie: `sass/style.scss`, natomiast jesli np mialabys Gruntfile w katalogu `grunt`, a sass poziom wyzej, to musialabys sie cofnac w sciezce, czyli `../style.scss`

Sciezki relatywne w przeciwienstwie do absolutnych sa bardziej uniwersalne. Ja np juz nie uruchomie Twojego grunta poniewaz nie mam takiej struktury katalogow jak: `/Desktop/Kodilla/Java-Script 2//workspace/style/style.sass`

**Comment by JoannaKu** [comment]
zrobione :)

**Comment by michal-bootcamp** [comment]
super, zmien jeszcze rozszerzenie pliku `style.scss.css` na `.scss`

**Comment by JoannaKu** [comment]
zrobione :)

**Comment by michal-bootcamp** [comment]
teraz jeszcze w tym `.gitignore` zamiast `*node_modules` powinno byc `node_modules/`

**Comment by JoannaKu** [comment]
ok, poprawione :)

**Comment by michal-bootcamp** [comment]
node_modules to katalog wiec brakuje ukosnika na koncu (.gitignore)

**Comment by JoannaKu** [comment]
poprawiłam. Nie zauważyłam, że wcześniej już mi napisałeś jak powinno być :)

**Comment by michal-bootcamp** [comment]
teraz super :)
